DROP DATABASE IF EXISTS `sunturk`;

CREATE DATABASE `sunturk`;

USE `sunturk`;

CREATE TABLE `gebruikers` (
    id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    wachtwoord VARCHAR(100) NOT NULL
);

CREATE TABLE `bestemmingen` (
    id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    plaats VARCHAR(100) NOT NULL,
    stad VARCHAR(100) NOT NULL,
    activiteit1 VARCHAR(100) NOT NULL,
    activiteit2 VARCHAR(100) NOT NULL,
    activiteit3 VARCHAR(100) NOT NULL,
    informatie TEXT NOT NULL,
    hotel VARCHAR(100) NOT NULL,
    restaurant VARCHAR(100) NOT NULL,
    foto VARCHAR(500) NOT NULL
);

INSERT INTO `bestemmingen` (`plaats`, `stad`, `activiteit1`, `activiteit2`, `activiteit3`, `informatie`, `hotel`, `restaurant`, `foto`) VALUES
    ('Basilica Cisterne', 'Istanbul', 'Historische museum', 'Concerten', 'Fotografiebezoek' ,'De Basilica Cisterne is niet alleen een historisch bouwwerk uit de Byzantijnse tijd, maar ook een levendig cultureel centrum in Istanbul. Als historisch museum biedt het bezoekers een indrukwekkende ondergrondse ervaring, waar je kunt leren over de waterhuishouding van het oude Constantinopel en iconische elementen zoals de Medusahoofden kunt bewonderen. Naast de vaste tentoonstelling wordt de cisterne regelmatig gebruikt als unieke locatie voor avondconcerten, waarbij klassieke muziek, wereldmuziek of experimentele optredens tot leven komen in de magische sfeer van het halfverlichte water. Voor fotografieliefhebbers is het een waar paradijs: de weerspiegelingen, het lichtspel en de architectuur zorgen voor onvergetelijke beelden. Bezoekers mogen vrij foto’s maken zonder flits, en voor professionele shoots is toestemming aan te vragen. De Basilica Cisterne is daarmee een plek waar geschiedenis, kunst en beleving samenkomen.', 'Vogue Hotel Supreme Istanbul', 'Serbethane Cafe & Restaurant', 'https://www.basilicacistern.gen.tr/wp-content/uploads/2023/10/Plan-Your-Visit-to-the-Basilica-Cistern-scaled.jpg'),
    ('The Land Of Legends Theme Park', 'Antalya', 'Attracties', 'Waterparken', 'Shows', 'The Land of Legends Theme Park in Antalya biedt een perfecte mix van spannende attracties, verfrissende waterparken en spectaculaire shows voor het hele gezin. Bezoekers kunnen genieten van adrenalineverhogende achtbanen zoals de Hyper Coaster en de unieke Typhoon Coaster waterachtbaan, terwijl het uitgebreide waterpark met glijbanen, golfslagbaden en lazy rivers volop waterplezier garandeert. Daarnaast zorgen indrukwekkende shows zoals de dolfijnenshow, de kindvriendelijke Masha en de Beer-voorstelling en de magische avondbootparade met muziek, licht en water voor onvergetelijk entertainment. Zo combineert het park avontuur, ontspanning en amusement op een unieke en veelzijdige manier.', 'The Land of Legends Kingdom Hotel', 'Sefin Yeri Restaurant', 'https://www.prettigreizen.nl/Pictures/H-31912252449.JPEG'),
    ('Ayasofya', 'Istanbul', 'Museum', 'Culturele evenementen', 'Religieuze plek', 'Aya Sofya is een indrukwekkend monument in Istanbul dat vroeger een museum was en tegenwoordig weer een moskee is. Het gebouw combineert prachtige Byzantijnse mozaïeken met islamitische kunst en is een unieke plek waar verschillende culturen samenkomen. Rondom Aya Sofya worden regelmatig culturele evenementen georganiseerd, zoals tentoonstellingen en muziekvoorstellingen, waardoor het niet alleen een historische bezienswaardigheid is, maar ook een levendige plek vol cultuur en geschiedenis.', 'Hagia Sofia Mansions Istanbul, Curio Collection by Hilton', 'Hagia Sophia Terrace Restaurant', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/54/be/42/hagia-sophia-museum-by.jpg?w=1200&h=1200&s=1'),
    ('Cappadocia', 'Nevsehir', 'Ballonvaart', 'Bezoek aan ondergrondse steden', 'ATV- of jeeptours', 'In Cappadocië is een ballonvaart een spectaculaire ervaring waarbij je vroeg in de ochtend opstijgt om te zweven over het adembenemende landschap van rotsformaties, valleien en sprookjesachtige schoorstenen, terwijl de zonsopgang de omgeving in warme kleuren hult. Naast deze luchtavonturen kun je ook de fascinerende ondergrondse steden bezoeken, zoals Derinkuyu en Kaymakli, waar eeuwenoude tunnels en kamers ooit dienden als veilige schuilplaatsen voor bewoners tijdens conflicten. Voor wie van actie houdt, zijn er daarnaast spannende ATV- of jeeptours die je meenemen over ruige paden en verborgen plekken, waardoor je het ruige en natuurlijke landschap van Cappadocië op een dynamische manier kunt verkennen.', 'Sultan Cave Suites', 'Topdeck Cave Restaurant', 'https://cdn-gaecj.nitrocdn.com/JMwuRIbFKRytZpZBQQGkRvqmTfGyKhHA/assets/images/optimized/rev-2ccb7ab/turkeytravelplanner.com/wp-content/uploads/2023/07/nevsehir-cappadocia-kapadokya.jpg'),
    ('Lara Beach', 'Antalya', 'Strand', 'Watersporten', 'Picknick', 'Lara Beach in Antalya biedt een perfecte combinatie van ontspanning en avontuur. Het uitgestrekte zandstrand is ideaal voor zonnebaden en zwemmen in het heldere water van de Middellandse Zee. Voor de actievelingen zijn er diverse watersportmogelijkheden zoals jetskiën, parasailen, windsurfen en bananenboottochten. Na een actieve ochtend is het heerlijk ontspannen met een picknick op het strand; er zijn speciale picknickzones met barbecuegrills, tafels en banken, perfect voor een gezellige lunch met uitzicht op zee. Of je nu wilt ontspannen in de zon, actief wilt zijn op het water of gewoon wilt genieten van een gezellige picknick, Lara Beach biedt voor ieder wat wils.', 'Titanic Deluxe Lara', 'Yakamoz Restaurant', 'https://a.loveholidays.com/media-library/~production/d72f2c4967fdffecf0a749b4c23d5c44ccd02708-5760x3700.jpg'),
    ('Oude stad Efeze', 'Izmir', 'Historische stad', 'Bibliotheek', 'Theater', 'De Bibliotheek van Celsus is een indrukwekkend gebouw met een prachtige gevel van hoge zuilen en gedetailleerde sculpturen. Het is een van de best bewaarde monumenten in Efeze en trekt veel bezoekers vanwege zijn mooie architectuur. Het Grote Theater is een enorm amfitheater dat vroeger plaats bood aan zo’n 25.000 mensen. Het is een indrukwekkende plek om rond te lopen en je voor te stellen hoe het was tijdens oude voorstellingen en evenementen. De Tempel van Artemis bestaat vandaag vooral uit enkele overgebleven zuilen en fundamenten, maar het blijft een indrukwekkende plek om te bezoeken vanwege de omvang en de sfeer die het uitstraalt.', 'Ephesus Palace Hotel', 'Selçuk Köftecisi', 'https://www.vakantiediscounter.nl/blog/wp-content/uploads/2017/06/cultuur-efeze-turkije.jpg'),
    ('Dolmabahçepaleis', 'Istanbul', 'Museum', 'Architectuur', 'Evenementen en concerten', 'Het Dolmabahçe-paleis fungeert ook als een indrukwekkend museum waar bezoekers een diepgaande blik kunnen werpen op het Ottomaanse rijk, met zorgvuldig bewaarde meubels, schilderijen en persoonlijke bezittingen van de sultans. Architectonisch is het paleis een unieke mix van Europese barok-, rococo- en neoklassieke stijlen, gecombineerd met traditionele Ottomaanse elementen, wat resulteert in een luxueuze en indrukwekkende uitstraling. Daarnaast worden er regelmatig evenementen en klassieke concerten georganiseerd in het paleis of de tuinen, die een sfeervolle en culturele ervaring bieden, waarbij bezoekers kunnen genieten van muziek en kunst in een historische setting.', 'Shangri-la Bosphorus', 'IST TOO', 'https://media1.thrillophilia.com/filestore/n4ivrvhng18c0dbxt2outm6qddti_Gate_of_Sultan_Dolmabahce_Palace_81a5647a39.jpg?w=400&dpr=2'),
    ('Marmaris Marina', 'Marmaris', 'Boottochten en Zeilen', 'Watersporten', 'Winkelen en Dineren', 'Marmaris Marina is een ideale uitvalsbasis voor allerlei activiteiten op en rond het water. Een van de populairste bezigheden is het maken van boottochten en zeiltochten langs de betoverende Turkse kustlijn. Je kunt kiezen voor een ontspannende dagtocht naar afgelegen baaien en eilanden, of een meer avontuurlijke zeilreis langs de Egeïsche Zee. Voor de liefhebbers van actie biedt de marina volop mogelijkheden voor watersporten, zoals jetskiën, parasailen, snorkelen en duiken in het kristalheldere water. Na een dag op zee is het heerlijk om te flaneren langs de jachthaven, waar je tal van winkels, boetieks en marktkraampjes vindt. Sluit je dag af in een van de sfeervolle restaurants of cafés, waar je kunt genieten van lokale Turkse gerechten, verse vis of een verfrissend drankje met uitzicht op de ondergaande zon.', 'Marmaris Bay Resort', 'Pineapple Restaurant', 'https://www.tyha.co.uk/GenerateImage.aspx?file=/images/galleries/gallery318/986_220%20m.jpg&resize=T&keepRatio=T&maxWidth=600&maxHeight=600'),
    ('Anadolu Medeniyetleri Muzesi', 'Ankara', 'Historische musea', 'Tentoonstellingen', 'Architectuur', 'Het Museum van Anatolische Beschavingen, gelegen in de Turkse hoofdstad Ankara, is een van de meest toonaangevende archeologische musea ter wereld. Het museum biedt een indrukwekkend overzicht van de rijke geschiedenis van Anatolië, vanaf het Paleolithicum tot de Romeinse tijd. De permanente tentoonstellingen zijn chronologisch geordend en tonen unieke artefacten uit onder meer de Hettitische, Frygische, Urartische en Lydische beschavingen, waaronder kleitabletten, beeldhouwwerken, wapens en sieraden. Het museum is gevestigd in twee prachtig gerestaureerde Ottomaanse gebouwen uit de 15e eeuw – een bedesten (overdekte markt) en een han (karavanserai) – die zelf ook historische waarde hebben. De combinatie van oude artefacten en authentieke architectuur maakt het museum tot een bijzondere plek waar geschiedenis letterlijk tot leven komt.', 'Divan Çukurhan', 'Sevilla Restaurant in Atakule', 'https://cdnuploads.aa.com.tr/uploads/Contents/2020/02/12/thumbs_b_c_1efb4dab87cf2540b6acb3d31376c610.jpg'),
    ('Kaleiçi', 'Antalya', 'Historische centrum', 'Museum', 'Boottocht', 'Het historische centrum van Antalya, Kaleiçi, is een sfeervolle wijk vol smalle, geplaveide straatjes, traditionele Ottomaanse huizen en oude stadsmuren die teruggaan tot de Romeinse tijd. In dit doolhof van geschiedenis vind je onder andere het Kaleiçi Museum, gevestigd in een gerestaureerd huis dat een goed beeld geeft van het leven in de Ottomaanse periode met meubels, kleding en kunstvoorwerpen uit die tijd. Vanuit de nabijgelegen oude haven kun je bovendien een boottocht maken langs de prachtige kust van Antalya, waarbij je uitzichten hebt op kliffen, watervallen en de helderblauwe zee – een perfecte combinatie van cultuur, natuur en ontspanning.', 'Hotel Karyatit Kaleiçi', 'Kaleici Steak Gastro Bar', 'https://www.themarmarahotels.com/hs-fs/hubfs/Kaleici%20(1)%20(1).jpg?width=1296&name=Kaleici%20(1)%20(1).jpg'),
    ('Cacabey Medresesi', 'Kirsehir', 'Astronomisch observatorium', 'Architectuur', 'Historisch monument', 'Cacabey Medresesi is een belangrijk historisch en cultureel monument in Kırşehir, waar bezoekers een unieke combinatie van wetenschap, kunst en erfgoed kunnen ervaren. Bij een bezoek aan het gebouw kun je ontdekken hoe het ooit dienstdeed als astronomisch centrum, met architectonische elementen die verwijzen naar de studie van de sterren. Tegelijkertijd biedt het gebouw een prachtig voorbeeld van Seltsjoekse architectuur, met gedetailleerde steenbewerking, geometrische patronen en karakteristieke bouwstijlen. Een wandeling door de medrese voelt als een reis door de tijd, waar je de rijke culturele waarde van deze plek kunt bewonderen.', 'Grand Hotel Terme', 'Aspava Sohretler Restaurant', 'https://turkmaarifansiklopedisi.org.tr/uploads/matter/original/caca-bey-medresesi-167ac8cf97b83e.webp'),
    ('Sumela Monastery', 'Trabzon', 'Oude ruines', 'Historische locaties', 'Natuur', 'Een bezoek aan het Sümela Monastery zelf is een indrukwekkende ervaring: het klooster is gebouwd tegen een steile klif en lijkt als het ware aan de rotswand te hangen, wat het tot een uniek staaltje Byzantijnse architectuur maakt. Binnenin bewonder je eeuwenoude fresco’s met religieuze taferelen, smalle doorgangen, kleine cellen, kapellen en een natuurlijke bron die als heilig wordt beschouwd. Rondom het klooster ligt het prachtige Altındere Nationaal Park, waar je heerlijk kunt wandelen door dichte bossen, langs kabbelende beekjes en over bergpaden met panoramisch uitzicht over de groene vallei. Het park biedt zowel korte wandelroutes als langere tochten voor natuurliefhebbers. Voor wie liever tot rust komt, zijn er in het park en in de omgeving ook veel plekken om te picknicken of te ontspannen in de natuur: houten tafels, schaduwrijke plekken onder de bomen en rustige plekjes bij het water maken het een ideale locatie om te genieten van een zelf meegebrachte lunch of simpelweg de rust van het berglandschap.', 'İSKALİTA Otel', 'Sumela Sosyal Tesisleri', 'https://seralakehotel.com/wp-content/uploads/2025/04/Sumela-Manastiri-Trabzon-1.webp'),
    ('Topkapi Paleis', 'Istanbul', 'Historische museum', 'Natuur', 'Tentoonstellingen', 'Het Topkapi Paleis is een van de belangrijkste historische bezienswaardigheden in Istanbul en diende eeuwenlang als het centrum van macht van het Ottomaanse Rijk. Gebouwd in de 15e eeuw door sultan Mehmet de Veroveraar, was het de residentie van Ottomaanse sultans en hun hofhouding. Sinds 1924 is het paleis opengesteld als museum en trekt het jaarlijks miljoenen bezoekers. In het museum zijn indrukwekkende tentoonstellingen te zien, zoals de keizerlijke schatkamer met juwelen en wapens, religieuze relikwieën die worden toegeschreven aan de profeet Mohammed, en zeldzame manuscripten, kleding en kalligrafie. Ook de beroemde harem kan bezocht worden met een apart ticket. Naast de rijke geschiedenis biedt het paleis prachtige binnenplaatsen en tuinen met uitzicht over de Bosphorus en de Gouden Hoorn, wat het tot een bijzondere plek maakt waar cultuur, natuur en erfgoed samenkomen.', 'Four Seasons Hotel at Sultanahmet', 'Matbah', 'https://cdn-imgix.headout.com/media/images/858959378598b81dfdff32444a0c400d-harem.jpg?auto=format&w=1222.3999999999999&h=687.6&q=90&ar=16%3A9&crop=faces&fit=crop'),
    ('Ölüdeniz', 'Muğla', 'Stad', 'Paragliding', 'Boottochten', 'Het strand van Ölüdeniz is een van de mooiste en meest iconische van Turkije, bekend om zijn fijne zand, kristalhelder water en de spectaculaire Blue Lagoon, waar je heerlijk kunt zwemmen, zonnebaden of watersporten beoefenen in een rustige omgeving. Naast ontspanning is Ölüdeniz ook een van de beste plekken ter wereld voor paragliding. Vanaf de nabijgelegen Babadağ-berg zweef je met een ervaren piloot over het adembenemende landschap, met uitzicht op de blauwe zee en de groene bergen – een onvergetelijke ervaring. Voor wie liever op het water blijft, zijn er dagelijks boottochten naar idyllische plekken zoals de Butterfly Valley, de Blue Cave, St. Nicholas Island en diverse onbewoonde baaien. Tijdens deze tochten kun je zwemmen, snorkelen of gewoon genieten van de zon en de natuur. Samen vormen het strand, de paragliding en de boottochten de perfecte mix van ontspanning en avontuur in Ölüdeniz.', 'Blue Star Hotel', 'Kumsal Pide', 'https://cdn.getyourguide.com/img/location/60f5b3fa10428.jpeg/99.jpg'),
    ('De Beşparmak Bergen', 'Beşparmak', 'Rotsklimmen', 'Kasteeltocht', 'Natuur', 'De Beşparmak-bergen, ook wel bekend als de Kyrenia-bergketen, vormen een ruig en indrukwekkend landschap in Noord-Cyprus dat ideaal is voor avonturiers en natuurliefhebbers. De kalkstenen kliffen en steile hellingen maken het gebied bijzonder geschikt voor rotsklimmen, met diverse routes voor zowel beginners als ervaren klimmers. Verspreid over de bergkam liggen eeuwenoude kastelen zoals St. Hilarion, Buffavento en Kantara, die samen een unieke kasteeltocht vormen. Deze versterkte bouwwerken, vaak spectaculair gelegen op hoge rotspunten, bieden niet alleen een blik op de middeleeuwse geschiedenis, maar ook adembenemende uitzichten over zee en land. Daarnaast herbergen de bergen een rijke biodiversiteit, met geurige dennenbossen, zeldzame bloemen, vlinders en trekvogels, waardoor elke tocht ook een diepe natuurbeleving wordt.', 'Hotel Pia Bella', 'Candle Light Restaurant & Bar', 'https://live.staticflickr.com/5582/14204916726_6e6ef1b656_b.jpg');

CREATE TABLE `commentsectie` (
	cid int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    uid varchar(128) NOT NULL,
    datum datetime NOT NULL,
    bericht TEXT NOT NULL
);